#!/usr/bin/env python3
"""Regenerate results_index.md and table_values.md from the canonical CSVs in
analysis/results/material_penetration/. These two docs used to be hand-maintained and
drifted out of sync with the pipeline (wrong ranking, references to deleted
files, stale row counts) -- this script is the fix: run it after
material_penetration_experiment.py and material_penetration_clear_figures.py
so the docs can't rot again.
"""
from __future__ import annotations

import os
from pathlib import Path

os.environ.setdefault("MPLCONFIGDIR", "/tmp/matplotlib")

import pandas as pd

BASE = Path(__file__).resolve().parents[2] / "analysis" / "results" / "material_penetration"

ALLOY_LABELS_SHORT = {
    "alloy1": "Alloy 1 (Cu)",
    "alloy2": "Alloy 2 (brass)",
    "alloy3": "Alloy 3 (CuNi 90/10)",
    "alloy4": "Alloy 4 (Al bronze)",
    "alloy5": "Alloy 5 (BeCu)",
}


def md_table(df: pd.DataFrame, floatfmt: str = "{:.4f}") -> list[str]:
    def fmt(v: object) -> str:
        if isinstance(v, float):
            return "" if pd.isna(v) else floatfmt.format(v)
        return str(v)

    header = "| " + " | ".join(df.columns) + " |"
    sep = "| " + " | ".join("---" for _ in df.columns) + " |"
    rows = ["| " + " | ".join(fmt(v) for v in row) + " |" for row in df.itertuples(index=False)]
    return [header, sep, *rows]


def main() -> None:
    spectrum_summary = pd.read_csv(BASE / "spectrum_summary.csv")
    xray_weights = pd.read_csv(Path(__file__).resolve().parents[2] / "spectra" / "150kvp_weights.csv")
    validation_checks = pd.read_csv(BASE / "validation_checks.csv")
    response = pd.read_csv(BASE / "detector_response.csv")
    attenuation = pd.read_csv(BASE / "alloy_attenuation.csv")
    combined = pd.read_csv(BASE / "combined_results.csv")
    transport = pd.read_csv(BASE / "transport_validation.csv")
    performance = pd.read_csv(BASE / "performance_evaluation.csv")
    bin_results = pd.read_csv(BASE / "per_detector_energy_bin_results.csv")
    discrimination = pd.read_csv(BASE / "alloy_discrimination_cnr.csv")

    real = performance[~performance["proxy_result"]].sort_values("rank_real_photon_counting_detectors")
    ranking_text = " > ".join(real["detector"])
    eiger2_transport = transport[transport["detector"] == "eiger2"]
    worst_eiger2_diff = eiger2_transport["relative_difference_pct"].abs().max()
    real_disc = discrimination[discrimination["detector"].isin(real["detector"])]
    hardest = real_disc.loc[real_disc["cnr"].idxmin()]
    easiest = real_disc.loc[real_disc["cnr"].idxmax()]

    index_lines = [
        "# Material Penetration Results Index",
        "",
        "This file points each methodology requirement to the exact result table. "
        "Auto-generated by `analysis/scripts/material_penetration_generate_docs.py` -- do not hand-edit, "
        "rerun the script instead after any pipeline change.",
        "",
        "D4 is Timepix3 CdTe: 1 mm CdTe, 55 um pitch, -300 V bias, 650e digitizer threshold (2.88 keV lower "
        "analysis edge, derived from the digitized threshold), and 4 ToT-derived analysis energy bins from "
        "2.88 to 120 keV.",
        "",
        "All `*_se` columns are binomial standard errors from the underlying 10k-event Monte Carlo runs "
        "(`SE = sqrt(p*(1-p)/n)`), propagated through to totals with energy bins treated as independent -- a "
        "labeled approximation, not an exact covariance propagation. See `binomial_se()` in "
        "`analysis/scripts/material_penetration_experiment.py`.",
        "",
        "## Presentation Visual Story",
        "",
        "Use these figures first when presenting. See `presentation_figure_guide.md` for the full, "
        "auto-generated caption text.",
        "",
        "| Step | Description | Figure |",
        "| --- | --- | --- |",
        "| 1 | Definition of the modeled incident X-ray source. | `presentation_figures/01_xray_source_model.png` |",
        "| 2 | Quantification of alloy attenuation strength across the spectrum. | `presentation_figures/02_alloy_transmission_heatmap.png` |",
        "| 3 | Characterization of each CdTe detector's energy-dependent response. | `presentation_figures/03_cdte_detector_response.png` |",
        "| 4 | Detected signal for all detector-alloy combinations. | `presentation_figures/04_detector_alloy_matrix_heatmap.png` |",
        "| 5 | Ranking of real photon-counting detectors by overall performance. | `presentation_figures/05_real_detector_performance.png` |",
        "| 6 | Energy-bin discrimination demonstrated via detected counts. | `presentation_figures/06_energy_bin_discrimination_alloy4.png` |",
        "| 7 | Validation of the analytical approximation against Monte Carlo transport (Medipix3). | `presentation_figures/07_transport_cross_check.png` |",
        "| 8 | Identification and correction of the analytical approximation's breakdown for EIGER2. | `presentation_figures/08_eiger2_transport_correction.png` |",
        "| 9 | Distinction between detected-count ranking and material-discrimination capability between alloy pairs. | `presentation_figures/09_alloy_discrimination_cnr.png` |",
        "",
        "Main interpretation:",
        "",
        f"> The 5 mm copper-alloy samples remove most low-energy photons, so the transmitted beam is strongly "
        f"hardened. Ranked by mean detected signal among real photon-counting detectors: {ranking_text}. "
        f"HEXITEC remains a spectroscopic proxy result, excluded from this ranking. EIGER2's analytic-vs-transport "
        f"gap (up to {worst_eiger2_diff:.0f}% at high energy, see section 1) meant its uncorrected ranking put it "
        f"last of the three real detectors; after applying its alloy2-calibrated transport correction it ranks "
        f"above Medipix3. Detected-count ranking (sections 5-6) answers a different question from material "
        f"discrimination (section 8): every detector struggles equally to tell {ALLOY_LABELS_SHORT.get(hardest['alloy_a'], hardest['alloy_a'])} "
        f"from {ALLOY_LABELS_SHORT.get(hardest['alloy_b'], hardest['alloy_b'])} apart (CNR~1), while "
        f"{ALLOY_LABELS_SHORT.get(easiest['alloy_a'], easiest['alloy_a'])} vs "
        f"{ALLOY_LABELS_SHORT.get(easiest['alloy_b'], easiest['alloy_b'])} is easy for all of them.",
        "",
        "## 1. Monte Carlo Photon Transport Results",
        "",
        "File: `transport_validation.csv` and plot: `transport_validation.png` (all 4 detectors) / "
        "`presentation_figures/07_transport_cross_check.png` (Medipix3) / "
        "`presentation_figures/08_eiger2_transport_correction.png` (EIGER2). This is the passive-alloy "
        "Geant4/Allpix validation against Alloy 2 brass: a 3-energy (40/80/120 keV) spot check for Medipix3, "
        "HEXITEC-proxy, and Timepix3, and a full 14-energy curve for EIGER2 (needed because EIGER2's hard 80 keV "
        "upper threshold makes the analytic shortcut miss Compton-downscattered photons re-entering its "
        "high-efficiency window -- see the relative_difference_pct column below).",
        "",
        *md_table(
            transport[
                [
                    "detector",
                    "energy_keV",
                    "validation_events",
                    "analytical_detected_counts",
                    "analytical_detected_counts_se",
                    "transport_detected_counts",
                    "transport_detected_counts_se",
                    "transport_detected_fraction",
                    "relative_difference_pct",
                    "status",
                ]
            ].round(4)
        ),
        "",
        "## 2. CdTe Detector Response",
        "",
        "File: `detector_response.csv` and plot: `detector_response.png`. This is the bare-detector response "
        "per incident photon (no alloy). `windowed_response` is the photon-equivalent response after "
        "threshold/energy-window logic; `windowed_response_se` is its binomial standard error.",
        "",
        *md_table(
            response[
                [
                    "detector",
                    "energy_keV",
                    "detected_event_count",
                    "intrinsic_response",
                    "threshold_window_acceptance",
                    "windowed_response",
                    "windowed_response_se",
                    "mean_cluster_energy_keV",
                    "proxy_result",
                ]
            ].round(4)
        ),
        "",
        "## 3. Photon Counting and Energy Discrimination With Energy-Bin Counts",
        "",
        "File: `detector_energy_bin_response.csv` (bare) and `per_detector_energy_bin_results.csv` "
        "(alloy-attenuated, includes `detection_method`). Timepix3 bins are ToT-derived analysis bins, "
        "not multiple hardware thresholds. EIGER2 rows use the alloy2-calibrated transport correction "
        "(see `detection_method` column and section 1).",
        "",
        *md_table(
            bin_results.groupby(
                ["detector", "alloy", "detector_energy_bin", "bin_low_keV", "bin_high_keV", "detection_method"],
                as_index=False,
            )["detected_in_detector_bin"]
            .sum()
            .sort_values(["detector", "alloy", "detector_energy_bin"])
            .round(2)
        ),
        "",
        "## 4. Transmission and Attenuation Calculations",
        "",
        "File: `alloy_attenuation.csv` and plot: `alloy_transmission.png`. This is the Beer-Lambert/XCOM-style "
        "calculation using `mu(E) = rho * sum(w_i * mu/rho_i)` and `T(E)=exp(-mu*x)`, from spekpy's NIST "
        "attenuation tables.",
        "",
        *md_table(
            attenuation[["alloy", "energy_keV", "mu_over_rho_cm2_g", "mu_linear_cm_inv", "transmission"]].round(6)
        ),
        "",
        "## 5. Detector-Alloy Simulation Matrix",
        "",
        "File: `combined_results.csv`, with per-energy detail in `per_energy_results.csv` (includes "
        "`detection_method`). This is the 4 detector x 5 alloy matrix at N0 = 1,000,000 photons.",
        "",
        *md_table(
            combined[
                [
                    "detector",
                    "alloy",
                    "incident_total",
                    "transmitted_total",
                    "detected_total",
                    "detected_total_se",
                    "detected_fraction_of_transmitted",
                    "mean_transmitted_energy_keV",
                    "beam_hardening_shift_keV",
                    "detection_method",
                    "proxy_result",
                ]
            ].round(2)
        ),
        "",
        "## 6. Performance Evaluation Table",
        "",
        "File: `performance_evaluation.csv`, generated by `build_performance_evaluation()` in "
        "`material_penetration_experiment.py`. HEXITEC is ranked in the full table but marked as proxy; the real "
        "photon-counting detector rank excludes HEXITEC. `detection_methods_used` shows which detectors rely on "
        "the EIGER2 transport correction.",
        "",
        *md_table(
            performance[
                [
                    "rank_all_detectors_by_mean_detected",
                    "rank_real_photon_counting_detectors",
                    "detector",
                    "proxy_result",
                    "mean_detected_total",
                    "mean_detected_total_se",
                    "mean_detected_fraction_of_incident",
                    "mean_detected_fraction_of_transmitted",
                    "best_alloy_by_detected_total",
                    "alloy_variation_cv",
                    "response_60keV",
                    "response_80keV",
                    "response_120keV",
                    "detection_methods_used",
                    "note",
                ]
            ].round(4)
        ),
        "",
        "## 7. Validation Checks",
        "",
        "File: `validation_checks.csv`.",
        "",
        *md_table(validation_checks),
        "",
        "## 8. Alloy Discrimination (CNR)",
        "",
        "File: `alloy_discrimination_cnr.csv` and plot: `presentation_figures/09_alloy_discrimination_cnr.png`. "
        "Pairwise material-discrimination CNR per detector -- `CNR = |N_a - N_b| / sqrt(N_a + N_b)` using each "
        "alloy's detected_total as signal and combined Poisson shot noise as the reference (electronic noise not "
        "included, so this is an upper bound on achievable discrimination). Answers a different question from "
        f"the ranking above: {ALLOY_LABELS_SHORT.get(hardest['alloy_a'], hardest['alloy_a'])} vs "
        f"{ALLOY_LABELS_SHORT.get(hardest['alloy_b'], hardest['alloy_b'])} is the hardest pair to distinguish "
        f"for every detector (CNR {hardest['cnr']:.1f}); "
        f"{ALLOY_LABELS_SHORT.get(easiest['alloy_a'], easiest['alloy_a'])} vs "
        f"{ALLOY_LABELS_SHORT.get(easiest['alloy_b'], easiest['alloy_b'])} is the easiest (CNR {easiest['cnr']:.1f}).",
        "",
        *md_table(
            discrimination[
                ["detector", "alloy_a", "alloy_b", "detected_total_a", "detected_total_b", "cnr", "proxy_result"]
            ].round(2)
        ),
        "",
    ]
    (BASE / "results_index.md").write_text("\n".join(index_lines), encoding="utf-8")

    table_lines = [
        "# Material Penetration Experiment Table Values",
        "",
        "These values come from the current analysis outputs in `analysis/results/material_penetration/`. "
        "Auto-generated by `analysis/scripts/material_penetration_generate_docs.py` -- do not hand-edit.",
        "",
        "## Validation Checks",
        "",
        *md_table(validation_checks),
        "",
        "## Spectrum Summary",
        "",
        *md_table(spectrum_summary.round(4)),
        "",
        "## Source Spectrum Weights",
        "",
        *md_table(xray_weights.round(6)),
        "",
        "## Bare Detector Response (windowed_response by energy)",
        "",
        *md_table(response.pivot(index="energy_keV", columns="detector", values="windowed_response").reset_index().round(4)),
        "",
        "## Alloy Transmission",
        "",
        *md_table(attenuation.pivot(index="energy_keV", columns="alloy", values="transmission").reset_index()),
        "",
        "## Combined Detector-Alloy Results",
        "",
        *md_table(
            combined[
                [
                    "detector",
                    "alloy",
                    "transmitted_total",
                    "detected_total",
                    "detected_fraction_of_transmitted",
                    "detection_method",
                    "proxy_result",
                ]
            ].round(2)
        ),
        "",
        "## Transport Cross-Check (all detectors)",
        "",
        *md_table(
            transport[
                [
                    "detector",
                    "energy_keV",
                    "validation_events",
                    "analytical_transmission",
                    "analytical_detected_counts",
                    "transport_detected_counts",
                    "transport_detected_fraction",
                    "relative_difference_pct",
                    "status",
                ]
            ].round(6)
        ),
        "",
        "## Alloy Discrimination (CNR)",
        "",
        *md_table(
            discrimination[["detector", "alloy_a", "alloy_b", "cnr"]].round(2)
        ),
        "",
    ]
    (BASE / "table_values.md").write_text("\n".join(table_lines), encoding="utf-8")
    print("Wrote results_index.md and table_values.md")


if __name__ == "__main__":
    main()
