[eiger2_detector]
type = "medipix3"
position = 0 0 0
orientation = 0 0 0
number_of_pixels = 256 256
pixel_size = 75um 75um
sensor_thickness = 750um
sensor_material = "cadmium_telluride"

[alloy2_brass_block]
role = "passive"
type = "box"
material = "G4_BRASS"
position = 0 0 -3mm
orientation = 0 0 0
size = 20mm 20mm 5mm
color = 0.85 0.58 0.16
opacity = 0.35
