[Allpix]
log_level = "WARNING"
number_of_events = 10000
detectors_file = "/data/simulation/configs/scenarios/material_penetration/detector_medipix3_bare.conf"
random_seed = 42

[GeometryBuilderGeant4]
world_material = "air"
world_minimum_margin = 10mm 10mm 15mm

[DepositionGeant4]
physics_list = QGSP_BERT
particle_type = "gamma"
source_energy = 20keV
source_type = "beam"
beam_size = 1mm
beam_direction = 0 0 1
source_position = 0 0 -1cm
number_of_particles = 1

[ElectricFieldReader]
model = "linear"
bias_voltage = -400V
depletion_voltage = -300V

[GenericPropagation]
temperature = 293K
charge_per_step = 10
mobility_model = "jacoboni"

[SimpleTransfer]
max_depth_distance = 5um

[DefaultDigitizer]
electronics_noise = 80e
threshold = 1129e
threshold_smearing = 80e

[DetectorHistogrammer]
